<h1>403 Forbidden</h1>
<p>
    <?php if ($error == 'error-unauthorized-controller') : ?>
        You are not authorized to access <?php echo($controller);?>
        <?php if ($action) : ?>
        ::<?php echo($action);?>Action()
        <?php endif;?>
        .
    <?php elseif ($error == 'error-unauthorized-route') : ?>
        You are not authorized to access <?php echo $route;?>.
    <?php else : ?>
    An unknown error occured.
    <?php endif;?>
</p>
